[package]
name = "orx-soa"
version = "1.0.0"
edition = "2024"
authors = ["orxfun <orx.ugur.arikan@gmail.com>"]
description = "Struct of arrays collections"
license = "MIT OR Apache-2.0"
repository = "https://github.com/orxfun/orx-soa/"
keywords = ["vec", "array", "vector", "soa"]
categories = ["data-structures", "algorithms", "no-std"]

[dependencies]
derive-new = { version = "0.7.0", default-features = false }
orx-parallel = { git = "https://github.com/orxfun/orx-parallel", branch = "collect-into-soa", default-features = false }
orx-priority-queue = { version = "1.9", default-features = false }
orx-soa-derive = { version = "1.2", default-features = false }

[dev-dependencies]
orx-parallel = { git = "https://github.com/orxfun/orx-parallel", branch = "collect-into-soa", default-features = false, features = [
    "std",
] }
